version: "3.8"
services:
  db:
    restart: always
    image: postgres:latest
    container_name: "testdb"
    env_file:
      - .env-dev
    ports:
      - "5432:5432"
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d
    networks:
      - postgres_network
networks:
 postgres_network:
  driver: bridge

volumes:
  db-store:
